### ISSUE TITLE
Create WorcShop Logo

### ISSUE THREAD

**Issue by Zarkast** [Worcshop/Administration#27]
Create Logo for WorkShop

**Comment by chrisdymaxion** [comment]
Contacted designer willing to volunteer time toward creating a logotype, provided current examples.

**Comment by NickBold** [comment]
Eric, the Technocopia designer is still very much interested and is already working on final drafts of the logos and company brand materials... which will be put up for review when they're ready.

Please let me know if a deadline appears that we need to be aware of.  But it shouldn't take too long.

**Comment by chrisdymaxion** [comment]
I'll tell my designer not to bother.

**Comment by NickBold** [comment]
WorcShop isn't happening anymore.
