### ISSUE TITLE
Please add Alex Gray to lists and emails

### ISSUE THREAD

**Issue by NickBold** [Worcshop/Administration#41]
Please add Alex Gray to project, he is getting his git hub set up.  (Whoever has permission)

His email is alex.gray.j@gmail.com please also add him to email lists (hand off to Angela)

**Comment by madhephaestus** [comment]
i need his github id

**Comment by NickBold** [comment]
He's still trying to get access to it, apparently he's having trouble accessing the email it was attached to so he can reset the password.

Please add his email to our mailing lists so he can get updates, and calendar invites.  Then pass this back off to me.  Hopefully he will have his github ID by then.

**Comment by NickBold** [comment]
He made a new GitHub account.

Void, please add his email to our email groups.  Then pass to Kevin.
Kevin, please add "InfDeath" to the GitHub project.

**Comment by VoidsCreations** [comment]
email groups? I can certainly include him in future emails if you get me his address, but I don't have any sort of group set up
Ang

Date: Tue, 3 Feb 2015 12:25:54 -0800

**Comment by madhephaestus** [comment]
@sjkelly It looks like you should set up that google group then?

**Comment by madhephaestus** [comment]
I added @InfDeath Alex Gray to the github, he needs to accept the invite

**Comment by sjkelly** [comment]
Google Groups: https://groups.google.com/forum/#!forum/worcshop

**Comment by madhephaestus** [comment]
can you add these emails to the group: 

1likeartemis@gmail.com,
"Nicholas Bold" <nick.bold@technocopia.org>,
"Randal Gardner" <randal.d.gardner@gmail.com>,
ferromorphics@gmail.com,
iamtheprocess@gmail.com,
jforjette@gmail.com,
julius@worcesterroots.org,
sjkelly@wpi.edu,
void_sansange@hotmail.com,
voidsansange@gmail.com,
voidsansange@hotmail.com,
whuffiepwrd@gmail.com

**Comment by sjkelly** [comment]
Invites should be sent out now.

**Comment by sjkelly** [comment]
All invitations to the mailing list were sent.
